#!/bin/sh
export QT_QPA_EGLFS_INTEGRATION=eglfs_kms
export QT_QPA_EGLFS_ALWAYS_SET_MODE=1
export QT_QPA_EGLFS_KMS_CONFIG=/etc/mxxf1.json
export QT_QPA_EGLFS_PHYSICAL_HEIGHT=158
export QT_QPA_EGLFS_PHYSICAL_WIDTH=211
export QT_QPA_PLATFORM=eglfs
