#!/bin/sh
#
### BEGIN INIT INFO
# Provides: prodtest
# Required-Start: $local_fs $remote_fs
# Required-Stop: $local_fs $remote_fs
# Default-Start:    5
# Default-Stop:     0 1 6
### END INIT INFO

killproc() {
        pid=`/bin/pidof $1`
        [ "$pid" != "" ] && kill $pid
}

case "$1" in
  start)
        . /etc/profile
        PATH=$PATH:/sbin /usr/bin/ppctest  >& /dev/null & /opt/rr/bin/rr  >& /dev/null &
  ;;

  stop)
        echo "Stopping prodtest"
        killproc rr
        killproc ppctest
  ;;

  restart)
	$0 stop
        sleep 1
        $0 start
  ;;

  *)
        echo "usage: $0 { start | stop | restart }"
  ;;
esac

exit 0
