#!/bin/sh

if [ -z "$1" ]; then
    echo "usage: buzzer [on/off]"
    exit 1
fi

f=$(find /sys/devices -name buzz)
if [ ! -z "$f" ]; then
    if echo $1 > $f; then
        exit 0
    else
        exit 1
    fi
fi

echo "No buzzer file"
exit 1
